# -*- coding: utf-8 -*-
"""lab04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCa1xWI_fLSDYwYMvCCMF1TMwh-YMCUK

# Q1
"""

class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def build_submission_tree(base_path: str, py102001033: str,py102001034: str) -> TreeNode:
   # Root node
    submissions_node = TreeNode(base_path)

   # Folders nodes
    py102001033_node = TreeNode(py102001033)
    py102001034_node = TreeNode(py102001034)

  # Folder to root
    submissions_node.left = py102001033_node
    submissions_node.right = py102001034_node

  # Files to folder
    def add_files(parent_node: TreeNode, files: list[str]):
      if not files:
        return

      parent_node.left = TreeNode(files[0])
      if len(files) > 1:
        parent_node.right = TreeNode(files[1])

    py102001033=["lab01.py","lab02.py"]
    py102001034=["lab03.py","lab04.py"]

    add_files(py102001033_node,py102001033)
    add_files(py102001034_node,py102001034)

    return submissions_node

"""# Q2"""

def postorder(submissions_node):
    if not submissions_node:
        return []
    return postorder(submissions_node.left) + postorder(submissions_node.right) + [submissions_node.value]


def print_all_nodes(submissions_node: TreeNode) -> None:

    for value in postorder(submissions_node):
        print(value)

"""# Q3"""

def find_py_files(submissions_node: TreeNode) -> list[str]:

    def build_path(node: TreeNode, path: str, result: list[str]):
        if not node:
            return

        current_path = f"{path}/{node.value}" if path else node.value
        if current_path.endswith(".py"):
            result.append(current_path)
        build_path(node.left, current_path, result)
        build_path(node.right, current_path, result)

    py_files = []
    build_path(submissions_node, "", py_files)

    return py_files