# -*- coding: utf-8 -*-
"""Lab 00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjKyW3ZYpPAe-Lwjv-UDVpRGeTu2UvQa
"""

Lab 00 — Submission Test

Purpose:
- Verify that you can upload a file
- Verify correct file name and folder
- Verify that GitHub Pull Request works

Instructions:
1. Do NOT change the function name.
2. Do NOT print anything.
3. Only modify the return value if needed.
"""


def submission_check():
    """
    Return your student ID as a string.

    Example:
    "PY102001001"
    """
    return "REPLACE_WITH_YOUR_STUDENT_ID"

def submission_check():
    return "PY102001033"